### PR TITLE
fix: Adjust `polars` extras definition

### PR DESCRIPTION
**Pull request by max-sixty**
Fixes a warning from #381

### CODE REVIEW

**Review by eitsupi — COMMENTED** [review]
I'm not familiar with poetry so I'm not sure what the difference is, but thanks.

**Comment by max-sixty** [comment]
> I'm not familiar with poetry so I'm not sure what the difference is, but thanks.

No prob. FYI I think the previous version was trying to install `polars` with _its_ extras `polars`...

**Comment by eitsupi** [comment]
Thank you, does CI not check for such things......?

**Comment by max-sixty** [comment]
It's just a warning, it seems. We could try and add something that creates an error on warnings; we do this in the main prql repo...

**Pull request merged**
