### PR TITLE
Add basic dbt grammar for relations

### PR DESCRIPTION
**Pull request by chamini2**
Based on https://github.com/prql/prql/issues/375, this would be an initial work on being able to process prql-dbt files.

My idea is it would be easy to later incorporate into https://github.com/fal-ai/fal with a script.

### CODE REVIEW

**Comment by rbpatt2019** [comment]
Nearly all the tests starting failing due to parsing errors near `table`,
but I'm not yet sure why.
Investigating...

Really appreciate the great work!

**Comment by rbpatt2019** [comment]
Found it. In `pyprql/lang/prql.py`, the definition of `From` wasn't updated to parse a `Relation` for the second parameter - it still expects `Name`.

**Review by charlie-sanders — COMMENTED** [review]
Can we change this class name to TestDBT

**Comment by chamini2** [comment]
I am getting parsing errors with the changes I introduced, it seems to fail on `table`. I will take a look next week what is going on.

Thanks for the feedback.

**Comment by max-sixty** [comment]
@chamini2 I really appreciate you doing this work and I'm keen to integrate closely with `fai`.

I think that this is probably closed by https://github.com/prql/prql/pull/571, now that we've centralized on the rust compiler so we can focus to the python work on building on top of that. We've also just added https://github.com/prql/dbt-prql. 

We would be interested on collaborating with `fai` more broadly though, let me know if you ever want to discuss that.

**Pull request closed without merging**
