### PR TITLE
fix: fix python versions

### PR DESCRIPTION
**Pull request by eitsupi**
IPython is not supporting python 3.7

### CODE REVIEW

**Comment by max-sixty** [comment]
Yes, I think even 3.8 is close to losing support in some packages... Thanks

**Comment by eitsupi** [comment]
I happened to be reading the GitHub Actions log and noticed this, I think the step to set up poetry is too clever for this use case.
Probably better to check it some other way.

https://github.com/PRQL/pyprql/pull/164/checks#step:5:14

```log
The currently activated Python version 3.7.16 is not supported by the project (^3.8).
Trying to find and use a compatible version. 
Using python3.10 (3.10.6)
Creating virtualenv pyprql-2JuVSC4c-py3.10 in /home/runner/.cache/pypoetry/virtualenvs
Installing dependencies from lock file
```

**Comment by max-sixty** [comment]
Hmmm. I had tried to make it simple — it used to rely on nox.

I _think_ we should only have that problem when it's an incompatible version, which is rare...

But ofc open to any changes!

**Comment by max-sixty** [comment]
BTW it's also fine to cut out the "middle" version if we want to reduce the testing burden. It's extremely unlikely that something would fail on 3.9 if it passes on 3.8 & 3.10...

**Comment by eitsupi** [comment]
> BTW it's also fine to cut out the "middle" version if we want to reduce the testing burden. It's extremely unlikely that something would fail on 3.9 if it passes on 3.8 & 3.10...

Definitely!
Perhaps one number for the minimal version (e.g. `3.8`) and something like `3.x` will suffice.
https://github.com/actions/setup-python/blob/main/docs/advanced-usage.md#matrix-testing

**Pull request merged**
