### PR TITLE
chore: update Python and poetry

### PR DESCRIPTION
**Pull request by eitsupi**

### CODE REVIEW

**Comment by eitsupi** [comment]
The latest poetry doesn't seem supporting Python 3.12...

**Comment by max-sixty** [comment]
Yeah — not surprised unfortunately — unlike many languages, python support takes a while to catch up to the latest version... we can leave this open, I suspect it'll start working in the next couple of months, maybe much sooner...

**Comment by max-sixty** [comment]
> Yeah — not surprised unfortunately — unlike many languages, python support takes a while to catch up to the latest version... we can leave this open, I suspect it'll start working in the next couple of months, maybe much sooner...

Actually this was overly pessimistic — it looks like the 3.12 error is coming from `greenlet` rather than poetry...

**Comment by max-sixty** [comment]
Looks like we're now waiting on https://github.com/duckdb/duckdb/pull/9222 to be released

**Comment by eitsupi** [comment]
No longer needed.

**Comment by eitsupi** [comment]
Now works.

**Comment by max-sixty** [comment]
Thanks @eitsupi !

**Pull request merged**
