### PR TITLE
refactor!: remove deprecated cli module and update dependencies

### PR DESCRIPTION
**Pull request by eitsupi**
Remove the cli module, which has been deprecated since pyprql 0.5.10 (released on PyPI on 2022-12-12) (#93), and update dependencies.

This PR also includes a configuration change for python-semantic-release (`major_on_zero = false`), making the release after this disruptive change `0.7.0` instead of `1.0.0`.

### CODE REVIEW

**Comment by eitsupi** [comment]
The CLI is very well done and I am impressed, but there are so many dependencies that it will probably need to be split into separate packages if it is to be revived.

**Review by max-sixty — APPROVED** [review]
Thanks. 

It was a wonderful project, it remains in the soul of PRQL even if not the repo...

**Comment by max-sixty** [comment]
Shall I release 0.7.0 from the main repo? It's slightly simpler of the versions stay aligned, unless we have a reason to deviate

**Comment by eitsupi** [comment]
> Shall I release 0.7.0 from the main repo? It's slightly simpler of the versions stay aligned, unless we have a reason to deviate

If that is your intention, I am happy to hold off on releasing pyprql.
(I just thought it was worth releasing because of the many additional features related to IPython magic.)

**Pull request merged**
